/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CompanyCompanyIdImport } from './routes/company/$companyId'

// Create/Update Routes

const CompanyCompanyIdRoute = CompanyCompanyIdImport.update({
  path: '/company/$companyId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/company/$companyId': {
      id: '/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/company/$companyId'
      preLoaderRoute: typeof CompanyCompanyIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface FileRoutesByFullPath {
  '/company/$companyId': typeof CompanyCompanyIdRoute
}

interface FileRoutesByTo {
  '/company/$companyId': typeof CompanyCompanyIdRoute
}

interface FileRoutesById {
  '/company/$companyId': typeof CompanyCompanyIdRoute
}

interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/company/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to: '/company/$companyId'
  id: '/company/$companyId'
  fileRoutesById: FileRoutesById
}

interface RootRouteChildren {
  CompanyCompanyIdRoute: typeof CompanyCompanyIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  CompanyCompanyIdRoute: CompanyCompanyIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/company/$companyId"
      ]
    },
    "/company/$companyId": {
      "filePath": "company/$companyId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
